### ISSUE TITLE
Unused appenders cause file system actions in yaml config

### ISSUE THREAD

**Issue by kikonen-fiksu** [TwP/logging#93]
I tried to have separate file configs for local development vs. production.

Having config file,
````yaml
common_appenders: &common_appenders
  appenders:
    - type      : RollingFile
      name      : rolling_file
      filename  : <%= "#{Rails.root}/log/#{Rails.env}.log" %>
     ...
    - type      : File
      name      : file
      filename  : <%= "#{Rails.root}/log/#{Rails.env}.log" %>
     ...
````
(yes, I'm doing ERB on that config file)

End result was a bit confusing, since even if "rolling_file" was not used at all, it's instantiated and it immediately performs log rotate for file. This causes naturally undesired effect on log file utilized by "file".
